# @url = https://backendcitas.herokuapp.com
@url = http://localhost:3000

###

POST {{url}}/usuarios/registro/
Content-Type: application/json

{
    "nombre": "Rosa",
    "apellidos": "Sabater",
    "telefono": "664456545",
    "email": "rosa@gmail.com",
    "password": "1234" 
}
###

GET {{url}}/usuarios/mostrar/
###

# @name resLogin
POST {{url}}/usuarios/login/
Content-Type: application/json

{
    "email": "rosa@gmail.com",
    "password": "1234" 
}
###
@token = {{resLogin.response.body.token}}

GET {{url}}/usuarios/logout/
Authorization: {{token}}