# @url = https://backendcitas.herokuapp.com
@url = http://localhost:3000

###

POST {{url}}/registro/
Content-Type: application/json

{
    "nombre": "Rosa",
    "apellidos": "Sabater",
    "telefono": "664456545",
    "email": "rosa@gmail.com",
    "password": "12345678" 
}
###

GET {{url}}/admin/usuarios/mostrar/
###

GET {{url}}/admin/usuarios/5f87031855bb7a09a44f20b0/

###
# @name resLogin
POST {{url}}/areaclientes/login/
Content-Type: application/json

{
    "email": "rosa@gmail.com",
    "password": "12345678" 
}
###
@token = {{resLogin.response.body.token}}

GET {{url}}/areaclientes/logout/
Authorization: {{token}}
###
POST {{url}}/areaclientes/nuevacita
Content-Type: application/json
Authorization: {{token}}

{
    "fecha": "2020-10-19 16:29",
    "usuarioId": "5f88935cf893a724f0e0f9d1",
    "motivo": "uuuuuUUUUUUUUUHHH"
}
###
GET {{url}}/areaclientes/citas/5f87031855bb7a09a44f20b0
Authorization: {{token}}
###
DELETE {{url}}/areaclientes/baja
Authorization: {{token}}

###
PUT {{url}}/areaclientes/cancelarcita/5f8958531e013729e8cf042d
Authorization: {{token}}

###